#!/usr/bin/env python3
"""
╔══════════════════════════════════════════════════════════════════════╗
║  EVolvAI — ChargerOptimizerGA  V1                                   ║
║  Physics-Constrained Resilient EV Charging Infrastructure Planner   ║
║                                                                      ║
║  IEEE IES Generative AI Challenge 2026                               ║
║  Module Owner: Lochan (Risk Engine & Optimizer)                      ║
╚══════════════════════════════════════════════════════════════════════╝

Implements an integer-coded Genetic Algorithm with Conditional Value-at-Risk
(CVaR) for optimizing EV charger placement across N candidate nodes. The
optimizer minimizes a multi-objective fitness combining CapEx, wait-time
penalties, grid-stress penalties, and tail-risk (99th-percentile CVaR) of
operating costs under extreme demand scenarios generated by the GCD-VAE.

Chromosome:  [c_1, c_2, ..., c_N]  where c_i ∈ {0, ..., MAX_PORTS_PER_NODE}
             represents the number of charging ports assigned to node i.
"""

from __future__ import annotations

import dataclasses
import logging
import time
from typing import Optional

import numpy as np
from numpy.typing import NDArray

import json
import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
try:
    from data_pipeline.evaluate_charger_placement import evaluate_charger_placement
except ImportError:
    pass

# ─────────────────────────────────────────────────────────────────────
# Logging
# ─────────────────────────────────────────────────────────────────────
logger = logging.getLogger(__name__)


# =====================================================================
# §1  CONFIGURATION DATACLASS
# =====================================================================
@dataclasses.dataclass(frozen=True)
class EVOptimizerConfig:
    """
    All hyper-parameters for the GA and risk engine live here.
    Frozen to prevent accidental mutation during a run.

    Attributes
    ----------
    pop_size : int
        Number of chromosomes in each generation.
    max_ports_per_node : int
        Upper bound on ports at any single candidate node.
    mutation_rate : float | None
        Per-gene mutation probability. Defaults to 1/N if None.
    crossover_rate : float
        Probability that two parents undergo crossover.
    tournament_size : int
        Number of individuals sampled per tournament selection round.
    elite_fraction : float
        Fraction of the population preserved via elitism each generation.
    cvar_alpha : float
        Confidence level for CVaR (e.g., 0.99 → 99th-percentile tail).
    capex_per_port : float
        Capital expenditure per installed charging port (USD).
    opex_per_kwh : float
        Operational cost per kWh served (USD).
    wait_time_penalty_weight : float
        Scalar multiplier on the wait-time penalty term.
    grid_penalty_weight : float
        Scalar multiplier on the grid-stress penalty term.
    grid_capacity_per_node : float
        Average port threshold per node before grid stress escalates.
    max_generations : int
        Termination criterion: maximum GA generations.
    convergence_window : int
        Terminate early if best fitness stagnates for this many gens.
    convergence_tol : float
        Minimum improvement in fitness to reset convergence counter.
    seed : int | None
        RNG seed for reproducibility. None → non-deterministic.
    """

    # ── GA core ──────────────────────────────────────────────────────
    pop_size: int = 100
    max_ports_per_node: int = 20
    mutation_rate: Optional[float] = None          # default: 1/N
    crossover_rate: float = 0.8
    tournament_size: int = 3
    elite_fraction: float = 0.05

    # ── CVaR / risk ──────────────────────────────────────────────────
    cvar_alpha: float = 0.99

    # ── Cost model ───────────────────────────────────────────────────
    capex_per_port: float = 15_000.0               # USD per port
    opex_per_kwh: float = 0.50                     # USD per kWh (Increased unserved penalty)
    wait_time_penalty_weight: float = 25000.0      # Heavily penalize long queues
    grid_penalty_weight: float = 1.0
    grid_capacity_per_node: float = 5.0            # soft cap

    # ── Termination ──────────────────────────────────────────────────
    max_generations: int = 300
    convergence_window: int = 30
    convergence_tol: float = 1e-4

    # ── Reproducibility ──────────────────────────────────────────────
    seed: Optional[int] = None


# =====================================================================
# §2  GRID PENALTY (DUMMY SURROGATE)
# =====================================================================
def get_grid_penalty_dummy(
    chromosome: NDArray[np.int32],
    grid_capacity_per_node: float,
    rng: np.random.Generator,
) -> float:
    """
    Dummy grid-stress penalty standing in for Akshay's AC power-flow
    surrogate.  Will be replaced by the real PyTorch surrogate once
    the physics engine API stabilises.

    Penalty logic
    -------------
    * Compute total installed ports and a soft capacity threshold
      (grid_capacity_per_node × N).
    * If total ports ≤ threshold → small linear penalty.
    * If total ports > threshold → exponential ramp to discourage
      gross over-provisioning that would violate grid constraints.
    * A tiny uniform noise term simulates stochastic grid volatility
      (e.g., renewable intermittency).

    Parameters
    ----------
    chromosome : 1-D int array  [N]
        Port counts per node.
    grid_capacity_per_node : float
        Average soft-cap per node.
    rng : numpy Generator
        For deterministic noise injection.

    Returns
    -------
    float
        Non-negative penalty value (lower is better).
    """
    n_nodes = chromosome.shape[0]
    total_ports = int(chromosome.sum())
    threshold = grid_capacity_per_node * n_nodes

    # ── base penalty: linear ramp ────────────────────────────────────
    if total_ports <= threshold:
        penalty = 0.01 * total_ports
    else:
        # exponential blow-up beyond threshold
        overshoot = (total_ports - threshold) / max(threshold, 1.0)
        penalty = 0.01 * threshold + np.exp(2.0 * overshoot) - 1.0

    # ── stochastic noise (grid volatility) ───────────────────────────
    noise = rng.uniform(0.0, 0.05 * (1.0 + total_ports / max(n_nodes, 1)))
    return float(penalty + noise)


# =====================================================================
# §3  CONDITIONAL VALUE-AT-RISK (CVaR)
# =====================================================================
def calculate_cvar(
    costs: NDArray[np.float64],
    alpha: float = 0.99,
) -> float:
    """
    Compute CVaR (Expected Shortfall) at confidence level *alpha*.

    CVaR answers: "Given that we are in the worst (1-α) fraction of
    outcomes, what is the expected cost?"  This is a *coherent* risk
    measure (sub-additive, monotone, positive-homogeneous, translation-
    invariant) — unlike plain VaR — making it ideal for tail-risk
    optimisation in resilience planning.

    Implementation (fully vectorised)
    ----------------------------------
    1. Compute VaR = np.quantile(costs, alpha).
    2. Mask costs > VaR → tail losses.
    3. CVaR = mean of tail losses.  If no cost strictly exceeds VaR
       (e.g., all scenarios identical), fall back to VaR itself.

    Parameters
    ----------
    costs : 1-D float array  [S]
        Total system cost under each of S demand scenarios.
    alpha : float
        Confidence level, e.g. 0.99 for 99th-percentile tail.

    Returns
    -------
    float
        CVaR value (lower is better in the minimisation sense).
    """
    # ── VaR: the alpha-quantile of the cost distribution ─────────────
    var = float(np.quantile(costs, alpha))

    # ── tail mask: costs strictly exceeding VaR ──────────────────────
    tail_mask = costs > var
    tail_losses = costs[tail_mask]

    # ── CVaR: conditional expectation beyond VaR ─────────────────────
    if tail_losses.size > 0:
        return float(np.mean(tail_losses))
    # degenerate case — all costs ≤ VaR (e.g., identical scenarios)
    return var


# =====================================================================
# §4  MULTI-OBJECTIVE FITNESS FUNCTION
# =====================================================================
def evaluate_fitness(
    chromosome: NDArray[np.int32],
    demand_scenarios: NDArray[np.float64],
    config: EVOptimizerConfig,
    rng: np.random.Generator,
    traffic_index_tensor: Optional[NDArray[np.float64]] = None,
) -> float:
    """
    Master fitness function combining four cost/penalty terms into a
    single scalar that the GA *minimises*.

    Terms
    -----
    1. **CapEx** — linear in total installed ports.
    2. **Wait-time penalty** — at each node i and each scenario s,
       wait time ∝ demand / max(ports, 1).  Summed across nodes,
       averaged across scenarios.  Captures user-experience quality.
    3. **Grid-stress penalty** — from the dummy surrogate (§2).
    4. **OpEx + tail risk (CVaR)** — per-scenario operating cost is
       opex_per_kwh × total demand served capped at capacity.
       The CVaR of this cost distribution quantifies resilience
       against 99th-percentile "black-swan" demand surges.

    Parameters
    ----------
    chromosome : 1-D int array  [N]
        Port counts per node.
    demand_scenarios : 2-D float array  [S, N]
        S demand scenarios (kW) across N nodes.  Rows are independent
        draws from the GCD-VAE's tail distribution.
    config : EVOptimizerConfig
        All cost/penalty weights and thresholds.
    rng : numpy Generator
        For the grid penalty noise.
    traffic_index_tensor : 1-D or 2-D float array, optional
        Multiplier representing commuter traffic jams affecting wait time.

    Returns
    -------
    float
        Composite fitness score (lower = better).
    """
    n_scenarios, n_nodes = demand_scenarios.shape
    # ports as float for vectorised arithmetic
    ports = chromosome.astype(np.float64)           # [N]
    total_ports = ports.sum()

    # ── 1. CapEx: linear cost of installation ────────────────────────
    capex = config.capex_per_port * total_ports

    # ── 2. Wait-time penalty (vectorised over scenarios × nodes) ─────
    #   Model: wait_time_{s,i} = demand_{s,i} / max(ports_i, 0.1)
    #   Higher demand with fewer ports → longer queues.
    safe_ports = np.maximum(ports, 0.1)             # [N]  avoid /0
    # demand_scenarios: [S, N],  safe_ports: [N] → broadcast → [S, N]
    wait_times = demand_scenarios / safe_ports       # [S, N]
    
    if traffic_index_tensor is not None:
        wait_times *= (1.0 + traffic_index_tensor)
        
    avg_wait_penalty = float(np.mean(np.sum(wait_times, axis=1)))
    wait_cost = config.wait_time_penalty_weight * avg_wait_penalty

    # ── 3. Grid-stress penalty ───────────────────────────────────────
    try:
        from data_pipeline.evaluate_charger_placement import evaluate_charger_placement
        # Chromosome contains the number of charging ports for each node.
        # Evaluate penalty on peak load (assuming worst-case static loading for the configuration)
        bus_ids = np.arange(n_nodes) + 2 # DistFlow generally uses buses 2-33
        power_kw = chromosome.astype(np.float64) * 50.0  # 50 kW per port
        grid_cost = config.grid_penalty_weight * evaluate_charger_placement(bus_ids, power_kw)
    except ImportError:
        grid_cost = config.grid_penalty_weight * get_grid_penalty_dummy(
            chromosome, config.grid_capacity_per_node, rng
        )

    # ── 4. OpEx + CVaR tail risk ─────────────────────────────────────
    #   Per-scenario OpEx: charge served = min(demand, port_capacity).
    #   Assume each port can serve ~50 kWh per time-step.
    port_capacity = ports * 50.0                    # [N] kWh capacity
    # Demand served per scenario: clipped to capacity
    served = np.minimum(demand_scenarios, port_capacity)   # [S, N]
    scenario_opex = config.opex_per_kwh * np.sum(served, axis=1)  # [S]

    # Unserved demand penalty: extra cost for demand exceeding capacity
    unserved = np.maximum(demand_scenarios - port_capacity, 0.0)
    unserved_penalty = 2.0 * config.opex_per_kwh * np.sum(unserved, axis=1)

    # Total scenario costs = opex + unserved penalty
    scenario_costs = scenario_opex + unserved_penalty  # [S]

    # CVaR of the scenario cost distribution
    cvar_cost = calculate_cvar(scenario_costs, alpha=config.cvar_alpha)

    # ── Composite fitness (all terms in USD-equivalent) ──────────────
    fitness = capex + wait_cost + grid_cost + cvar_cost
    return float(fitness)


# =====================================================================
# §5  GENETIC ALGORITHM ENGINE
# =====================================================================
class ChargerOptimizerGA:
    """
    Integer-coded Genetic Algorithm for resilient EV charger placement.

    Lifecycle
    ---------
    1. Instantiate with config + node count.
    2. Call :meth:`run` with a demand-scenario tensor.
    3. Best chromosome, fitness, and convergence history are returned.

    Key operators
    -------------
    * **Tournament selection** — pressure-tuneable via tournament_size.
    * **Two-point crossover** — preserves geographic clusters because
      adjacent genes map to spatially nearby nodes.
    * **Integer-reset mutation** — per-gene probability; resets to a
      uniform-random valid port count (avoids gradient-like creep).
    * **Elitism** — top fraction survives intact to next generation.
    """

    def __init__(
        self,
        config: EVOptimizerConfig,
        n_nodes: int,
    ) -> None:
        """
        Parameters
        ----------
        config : EVOptimizerConfig
            Frozen hyper-parameter object.
        n_nodes : int
            Number of candidate charging nodes (chromosome length).
        """
        self.config = config
        self.n_nodes = n_nodes

        # Resolve default mutation rate: 1/N
        self.mutation_rate = (
            config.mutation_rate
            if config.mutation_rate is not None
            else 1.0 / n_nodes
        )

        # Number of elite individuals preserved each generation
        self.n_elite = max(1, int(config.elite_fraction * config.pop_size))

        # Deterministic RNG for reproducibility
        self.rng = np.random.default_rng(config.seed)

        # Populated by run()
        self.population: Optional[NDArray[np.int32]] = None
        self.fitness_values: Optional[NDArray[np.float64]] = None
        self.best_chromosome: Optional[NDArray[np.int32]] = None
        self.best_fitness: float = np.inf
        self.history: list[dict] = []

    # ─────────────────────────────────────────────────────────────────
    # §5.1  Population Initialisation
    # ─────────────────────────────────────────────────────────────────
    def initialize_population(self) -> NDArray[np.int32]:
        """
        Create a random initial population of integer chromosomes.

        Each gene c_i is drawn uniformly from {0, ..., max_ports_per_node}.
        Uses vectorised rng.integers for speed.

        Returns
        -------
        population : 2-D int array  [pop_size, n_nodes]
        """
        self.population = self.rng.integers(
            low=0,
            high=self.config.max_ports_per_node + 1,  # exclusive upper bound
            size=(self.config.pop_size, self.n_nodes),
            dtype=np.int32,
        )
        logger.debug(
            "Initialised population: shape=%s, dtype=%s",
            self.population.shape,
            self.population.dtype,
        )
        return self.population

    # ─────────────────────────────────────────────────────────────────
    # §5.2  Fitness Evaluation (batch)
    # ─────────────────────────────────────────────────────────────────
    def _evaluate_population(
        self,
        demand_scenarios: NDArray[np.float64],
        traffic_index_tensor: Optional[NDArray[np.float64]] = None,
    ) -> NDArray[np.float64]:
        """
        Evaluate fitness for every chromosome in the current population.

        Parameters
        ----------
        demand_scenarios : 2-D float array  [S, N]

        Returns
        -------
        fitness_values : 1-D float array  [pop_size]
        """
        pop = self.population
        fit = np.empty(pop.shape[0], dtype=np.float64)
        for i in range(pop.shape[0]):
            fit[i] = evaluate_fitness(
                pop[i], demand_scenarios, self.config, self.rng, traffic_index_tensor
            )
        self.fitness_values = fit
        return fit

    # ─────────────────────────────────────────────────────────────────
    # §5.3  Tournament Selection
    # ─────────────────────────────────────────────────────────────────
    def tournament_selection(self) -> NDArray[np.int32]:
        """
        Select one parent via tournament selection.

        Procedure
        ---------
        1. Sample *tournament_size* random indices from the population.
        2. Return the chromosome with the *lowest* fitness (minimisation).

        Returns
        -------
        parent : 1-D int array  [N]
        """
        # draw tournament_size random indices without replacement
        indices = self.rng.choice(
            self.config.pop_size,
            size=self.config.tournament_size,
            replace=False,
        )
        # pick the index with minimum fitness
        best_idx = indices[np.argmin(self.fitness_values[indices])]
        return self.population[best_idx].copy()

    # ─────────────────────────────────────────────────────────────────
    # §5.4  Two-Point Crossover
    # ─────────────────────────────────────────────────────────────────
    def two_point_crossover(
        self,
        parent_a: NDArray[np.int32],
        parent_b: NDArray[np.int32],
    ) -> tuple[NDArray[np.int32], NDArray[np.int32]]:
        """
        Two-point crossover that preserves geographic clusters.

        If both parents encode strong local solutions in different
        spatial regions of the charging network, two-point crossover
        can combine those regions intact — a key advantage for
        spatially-structured problems.

        Parameters
        ----------
        parent_a, parent_b : 1-D int arrays  [N]

        Returns
        -------
        child_a, child_b : 1-D int arrays  [N]
        """
        if self.rng.random() > self.config.crossover_rate:
            # no crossover — return clones
            return parent_a.copy(), parent_b.copy()

        n = self.n_nodes
        # choose two distinct cut points
        pts = np.sort(self.rng.choice(n, size=2, replace=False))
        pt1, pt2 = int(pts[0]), int(pts[1])

        child_a = parent_a.copy()
        child_b = parent_b.copy()

        # swap the segment between pt1 and pt2
        child_a[pt1:pt2] = parent_b[pt1:pt2]
        child_b[pt1:pt2] = parent_a[pt1:pt2]

        return child_a, child_b

    # ─────────────────────────────────────────────────────────────────
    # §5.5  Integer-Reset Mutation
    # ─────────────────────────────────────────────────────────────────
    def mutate_integer_reset(
        self,
        chromosome: NDArray[np.int32],
    ) -> NDArray[np.int32]:
        """
        Per-gene mutation: with probability *mutation_rate*, reset a
        gene to a uniformly random valid integer in
        {0, ..., max_ports_per_node}.

        Unlike Gaussian creep mutation (which biases towards small
        changes), integer-reset ensures the algorithm can escape local
        optima by jumping to any valid allele in one step.

        Parameters
        ----------
        chromosome : 1-D int array  [N]  (modified in-place)

        Returns
        -------
        chromosome : same array, mutated in-place.
        """
        # vectorised: draw a mask of which genes mutate
        mask = self.rng.random(self.n_nodes) < self.mutation_rate
        n_mutate = int(mask.sum())
        if n_mutate > 0:
            chromosome[mask] = self.rng.integers(
                low=0,
                high=self.config.max_ports_per_node + 1,
                size=n_mutate,
                dtype=np.int32,
            )
        return chromosome

    # ─────────────────────────────────────────────────────────────────
    # §5.6  Evolve — Single-Generation Step
    # ─────────────────────────────────────────────────────────────────
    def _evolve_one_generation(
        self,
        demand_scenarios: NDArray[np.float64],
        traffic_index_tensor: Optional[NDArray[np.float64]] = None,
    ) -> None:
        """
        Execute one full generation of the GA:
          1. Elitism — copy top individuals directly.
          2. Selection + crossover + mutation to fill remaining slots.
          3. Re-evaluate fitness on the new population.

        Parameters
        ----------
        demand_scenarios : 2-D float array  [S, N]
        """
        pop_size = self.config.pop_size

        # ── sort population by fitness (ascending = best first) ──────
        sorted_indices = np.argsort(self.fitness_values)
        sorted_pop = self.population[sorted_indices]

        # ── elitism: carry forward top individuals ───────────────────
        new_pop = np.empty_like(self.population)
        new_pop[: self.n_elite] = sorted_pop[: self.n_elite]

        # ── fill remaining slots via selection + crossover + mutation ─
        idx = self.n_elite
        while idx < pop_size:
            parent_a = self.tournament_selection()
            parent_b = self.tournament_selection()
            child_a, child_b = self.two_point_crossover(parent_a, parent_b)
            child_a = self.mutate_integer_reset(child_a)
            child_b = self.mutate_integer_reset(child_b)

            new_pop[idx] = child_a
            idx += 1
            if idx < pop_size:
                new_pop[idx] = child_b
                idx += 1

        self.population = new_pop
        self._evaluate_population(demand_scenarios, traffic_index_tensor)

    # ─────────────────────────────────────────────────────────────────
    # §5.7  Main Run Loop
    # ─────────────────────────────────────────────────────────────────
    def run(
        self,
        demand_scenarios: NDArray[np.float64],
        verbose: bool = True,
        traffic_index_tensor: Optional[NDArray[np.float64]] = None,
    ) -> dict:
        """
        Full GA optimisation loop.

        Parameters
        ----------
        demand_scenarios : 2-D float array  [S, N]
            S extreme demand scenarios across N nodes, typically
            generated by the GCD-VAE's tail sampling.
        verbose : bool
            Print per-generation stats to stdout.

        Returns
        -------
        result : dict
            best_chromosome : 1-D int array  [N]
            best_fitness    : float
            history         : list[dict]  per-generation stats
            generations     : int         total generations executed
            converged       : bool        True if early-stopped
        """
        t_start = time.perf_counter()

        # ── validate inputs ──────────────────────────────────────────
        assert demand_scenarios.ndim == 2, (
            f"demand_scenarios must be 2-D [S, N], got shape "
            f"{demand_scenarios.shape}"
        )
        assert demand_scenarios.shape[1] == self.n_nodes, (
            f"demand_scenarios has {demand_scenarios.shape[1]} nodes, "
            f"expected {self.n_nodes}"
        )

        # ── initialise ──────────────────────────────────────────────
        self.initialize_population()
        self._evaluate_population(demand_scenarios, traffic_index_tensor)
        self.history = []

        # track convergence
        stagnation_counter = 0
        prev_best = np.inf

        if verbose:
            print(
                f"{'Gen':>5} │ {'Best':>14} │ {'Mean':>14} │ "
                f"{'Worst':>14} │ {'Stag':>4}"
            )
            print("──────┼────────────────┼────────────────┼"
                  "────────────────┼──────")

        # ── generation loop ──────────────────────────────────────────
        for gen in range(self.config.max_generations):
            # record stats
            best_fit = float(np.min(self.fitness_values))
            mean_fit = float(np.mean(self.fitness_values))
            worst_fit = float(np.max(self.fitness_values))
            best_idx = int(np.argmin(self.fitness_values))

            gen_stats = {
                "generation": gen,
                "best_fitness": best_fit,
                "mean_fitness": mean_fit,
                "worst_fitness": worst_fit,
                "best_total_ports": int(self.population[best_idx].sum()),
            }
            self.history.append(gen_stats)

            # update global best
            if best_fit < self.best_fitness:
                self.best_fitness = best_fit
                self.best_chromosome = self.population[best_idx].copy()

            # convergence check
            improvement = prev_best - best_fit
            if improvement < self.config.convergence_tol:
                stagnation_counter += 1
            else:
                stagnation_counter = 0
            prev_best = best_fit

            if verbose and (
                gen % 10 == 0
                or gen == self.config.max_generations - 1
                or stagnation_counter >= self.config.convergence_window
            ):
                print(
                    f"{gen:>5} │ {best_fit:>14,.2f} │ {mean_fit:>14,.2f} │ "
                    f"{worst_fit:>14,.2f} │ {stagnation_counter:>4}"
                )

            # early stopping
            if stagnation_counter >= self.config.convergence_window:
                if verbose:
                    print(
                        f"\n⚡ Converged at generation {gen} "
                        f"(stagnant for {self.config.convergence_window} gens)"
                    )
                break

            # evolve to next generation
            self._evolve_one_generation(demand_scenarios, traffic_index_tensor)

        elapsed = time.perf_counter() - t_start
        converged = stagnation_counter >= self.config.convergence_window

        if verbose:
            print(f"\n🏁 Optimisation complete in {elapsed:.2f}s")
            print(f"   Best fitness : {self.best_fitness:,.2f}")
            print(
                f"   Total ports  : "
                f"{int(self.best_chromosome.sum())}"
            )
            print(f"   Generations  : {gen + 1}")
            print(f"   Converged    : {converged}")

        import json
        import os
        
        # Save output to output/final_optimal_layout.json
        output_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "output")
        os.makedirs(output_dir, exist_ok=True)
        final_layout = {"bus_ids": (np.arange(self.n_nodes) + 2).tolist(), "power_kw": (self.best_chromosome * 50.0).tolist()}
        with open(os.path.join(output_dir, 'final_optimal_layout.json'), 'w') as f:
            json.dump(final_layout, f)

        return {
            "best_chromosome": self.best_chromosome,
            "best_fitness": self.best_fitness,
            "history": self.history,
            "generations": gen + 1,
            "converged": converged,
            "elapsed_seconds": elapsed,
        }


# =====================================================================
# §6  STANDALONE DEMO
# =====================================================================
def _demo() -> None:
    """
    Quick smoke-test: run the GA on synthetic demand data and print
    results.  Invoked via `python -m risk_engine.optimizer_ga`.
    """
    # ── configuration ────────────────────────────────────────────────
    N_NODES = 32
    N_SCENARIOS = 200
    config = EVOptimizerConfig(
        pop_size=80,
        max_ports_per_node=20,
        cvar_alpha=0.99,
        max_generations=150,
        convergence_window=25,
        seed=42,
    )

    # ── demand: load Sujay's generated tensor if available ─────────────────
    rng = np.random.default_rng(config.seed)
    tensor_path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "output", "extreme_winter_storm.npy")
    if os.path.exists(tensor_path):
        print(f"Using generated tensor: {tensor_path}...")
        demand_scenarios = np.load(tensor_path)
        # Squeeze or format to [S, N] correctly
        if demand_scenarios.ndim == 3: 
            demand_scenarios = demand_scenarios.max(axis=1) # take max across the 24h
        if demand_scenarios.shape[1] > N_NODES:
            demand_scenarios = demand_scenarios[:, :N_NODES]
        elif demand_scenarios.shape[1] < N_NODES:
            demand_scenarios = np.pad(demand_scenarios, ((0, 0), (0, N_NODES - demand_scenarios.shape[1])))
    else:
        demand_scenarios = rng.lognormal(
            mean=3.0, sigma=0.8, size=(N_SCENARIOS, N_NODES)
        )
        # inject a few extreme "black-swan" scenarios
        demand_scenarios[-10:] *= 3.0

    print("=" * 64)
    print("  EVolvAI — ChargerOptimizerGA V1 Demo")
    print("=" * 64)
    print(f"  Nodes: {N_NODES}  |  Scenarios: {N_SCENARIOS}")
    print(f"  Pop: {config.pop_size}  |  Max gens: {config.max_generations}")
    print(f"  CVaR α: {config.cvar_alpha}")
    print("=" * 64 + "\n")

    # ── run ───────────────────────────────────────────────────────────
    ga = ChargerOptimizerGA(config=config, n_nodes=N_NODES)
    result = ga.run(demand_scenarios, verbose=True)

    # ── display best solution ────────────────────────────────────────
    best = result["best_chromosome"]
    print("\n📍 Best chromosome (ports per node):")
    for i, ports in enumerate(best):
        bar = "█" * ports
        print(f"   Node {i:>2}: {ports:>2} ports  {bar}")
    print(f"\n   Total ports: {best.sum()}")


if __name__ == "__main__":
    _demo()
